# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
  test:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - run:
          name: Test
          command: mvn test
  deploy:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - run:
          name: deploy to aws
          command: echo app deployed success ...




workflows:
  ibo_wfw:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test